# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(404, 388)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_icon = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_icon.sizePolicy().hasHeightForWidth())
        self.lbl_icon.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_icon.setFont(font)
        self.lbl_icon.setText("")
        self.lbl_icon.setPixmap(QtGui.QPixmap(":/icons/box"))
        self.lbl_icon.setObjectName("lbl_icon")
        self.horizontalLayout_3.addWidget(self.lbl_icon)
        self.label_3 = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.path_line = QtWidgets.QLineEdit(Dialog)
        self.path_line.setObjectName("path_line")
        self.horizontalLayout.addWidget(self.path_line)
        self.btn_browser = QtWidgets.QToolButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.btn_browser.setFont(font)
        self.btn_browser.setObjectName("btn_browser")
        self.horizontalLayout.addWidget(self.btn_browser)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.list_widget = QtWidgets.QListWidget(Dialog)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.list_widget.setFont(font)
        self.list_widget.setStyleSheet("QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical {\n"
"background: none;\n"
"}\n"
"QScrollBar:vertical {\n"
"     border: 2px solid grey;\n"
"     background: #B8C6D9;\n"
"     width: 15px;\n"
"     margin: 5px 0 5px 0;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"     background: #F2F2F2;\n"
"     min-height: 5px;\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: 2px solid grey;\n"
"     background: #B8C6D9;\n"
"     height: 5px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::sub-line:vertical {\n"
"     border: 2px solid grey;\n"
"     background: #B8C6D9;\n"
"     height: 5px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"")
        self.list_widget.setResizeMode(QtWidgets.QListView.Adjust)
        self.list_widget.setViewMode(QtWidgets.QListView.ListMode)
        self.list_widget.setObjectName("list_widget")
        self.gridLayout.addWidget(self.list_widget, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_load = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.btn_load.setFont(font)
        self.btn_load.setObjectName("btn_load")
        self.horizontalLayout_2.addWidget(self.btn_load)
        self.btn_close = QtWidgets.QPushButton(Dialog)
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        self.btn_close.setFont(font)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_2.addWidget(self.btn_close)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Assets Loader - [BETA]"))
        self.label_3.setText(_translate("Dialog", "Assets Loader"))
        self.label.setText(_translate("Dialog", "Assets Directory"))
        self.btn_browser.setText(_translate("Dialog", "..."))
        self.btn_load.setText(_translate("Dialog", "Load"))
        self.btn_close.setText(_translate("Dialog", "Close"))
from .resources import resources
